# Project works with use_frameworks!
#use_frameworks!

platform :ios, '13.0'

target 'SodiumPoc_Example' do
  pod 'SodiumPoc', :path => '../'

  target 'SodiumPoc_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.2.0'
    pod 'Nimble', '~> 8.0.7'
  end
end
